INSERT INTO USERS (USER_ID,FIRST_NAME,LAST_NAME) VALUES (USERS_ID_USER.NEXTVAL,'Romain','DALICHAMP');
INSERT INTO USERS (USER_ID,FIRST_NAME,LAST_NAME) VALUES (USERS_ID_USER.NEXTVAL,'Thierno-Amirou','DIALLO');
INSERT INTO USERS (USER_ID,FIRST_NAME,LAST_NAME) VALUES (USERS_ID_USER.NEXTVAL,'Jeremi','GRENIER-BERTHIAUME');
INSERT INTO USERS (USER_ID,FIRST_NAME,LAST_NAME) VALUES (USERS_ID_USER.NEXTVAL,'Morgane','RENARD');